In [1]:
import joblib
import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# =========================================================
# 1. LOAD DATA SPLIT DAN MODEL
# =========================================================
data = np.load("split_data.npz", allow_pickle=True)

X_test = data["X_test"]
y_test = data["y_test"]

model_nb = joblib.load("model_naive_bayes.pkl")
model_nb_pso = joblib.load("model_naive_bayes_pso.pkl")

# =========================================================
# 2. EVALUASI NAIVE BAYES
y_pred_nb = model_nb.predict(X_test)

acc_nb = accuracy_score(y_test, y_pred_nb)
precision_nb = precision_score(y_test, y_pred_nb, average="weighted", zero_division=0)
recall_nb = recall_score(y_test, y_pred_nb, average="weighted", zero_division=0)
f1_nb = f1_score(y_test, y_pred_nb, average="weighted", zero_division=0)
cm_nb = confusion_matrix(y_test, y_pred_nb)

print("\n=== HASIL EVALUASI NAIVE BAYES ===")
print("Accuracy :", acc_nb)
print("Precision:", precision_nb)
print("Recall   :", recall_nb)
print("F1-Score :", f1_nb)
print("\nClassification Report Naive Bayes:")
print(classification_report(y_test, y_pred_nb, zero_division=0))

print("\nConfusion Matrix Naive Bayes:")
print(cm_nb)

# simpan hasil evaluasi NB
hasil_eval_nb = pd.DataFrame([{
    "model": "Naive Bayes",
    "accuracy": acc_nb,
    "precision_weighted": precision_nb,
    "recall_weighted": recall_nb,
    "f1_score_weighted": f1_nb
}])

hasil_eval_nb.to_csv("hasil_evaluasi_naive_bayes.csv", index=False)

# simpan confusion matrix NB
cm_nb_df = pd.DataFrame(cm_nb)
cm_nb_df.to_csv("confusion_matrix_naive_bayes.csv", index=False)
# simpan prediksi NB
prediksi_nb = pd.DataFrame({
    "aktual": y_test,
    "prediksi": y_pred_nb
})
prediksi_nb.to_csv("prediksi_naive_bayes.csv", index=False)

# =========================================================
# 3. EVALUASI NAIVE BAYES + PSO
# =========================================================
y_pred_nb_pso = model_nb_pso.predict(X_test)

acc_nb_pso = accuracy_score(y_test, y_pred_nb_pso)
precision_nb_pso = precision_score(y_test, y_pred_nb_pso, average="weighted", zero_division=0)
recall_nb_pso = recall_score(y_test, y_pred_nb_pso, average="weighted", zero_division=0)
f1_nb_pso = f1_score(y_test, y_pred_nb_pso, average="weighted", zero_division=0)
cm_nb_pso = confusion_matrix(y_test, y_pred_nb_pso)

print("\n=== HASIL EVALUASI NAIVE BAYES + PSO ===")
print("Accuracy :", acc_nb_pso)
print("Precision:", precision_nb_pso)
print("Recall   :", recall_nb_pso)
print("F1-Score :", f1_nb_pso)
print("\nClassification Report Naive Bayes + PSO:")
print(classification_report(y_test, y_pred_nb_pso, zero_division=0))
print("\nConfusion Matrix Naive Bayes + PSO:")
print(cm_nb_pso)

# simpan hasil evaluasi NB + PSO
hasil_eval_nb_pso = pd.DataFrame([{
    "model": "Naive Bayes + PSO",
    "accuracy": acc_nb_pso,
    "precision_weighted": precision_nb_pso,
    "recall_weighted": recall_nb_pso,
    "f1_score_weighted": f1_nb_pso
}])

hasil_eval_nb_pso.to_csv("hasil_evaluasi_naive_bayes_pso.csv", index=False)

# simpan confusion matrix NB + PSO
cm_nb_pso_df = pd.DataFrame(cm_nb_pso)
cm_nb_pso_df.to_csv("confusion_matrix_naive_bayes_pso.csv", index=False)

# simpan prediksi NB + PSO
prediksi_nb_pso = pd.DataFrame({
    "aktual": y_test,
    "prediksi": y_pred_nb_pso
})
prediksi_nb_pso.to_csv("prediksi_naive_bayes_pso.csv", index=False)

# =========================================================
# 4. INFORMASI FILE OUTPUT
# =========================================================
print("\nFile output evaluasi:")
print("1. hasil_evaluasi_naive_bayes.csv")
print("2. confusion_matrix_naive_bayes.csv")
print("3. prediksi_naive_bayes.csv")
print("4. hasil_evaluasi_naive_bayes_pso.csv")
print("5. confusion_matrix_naive_bayes_pso.csv")
print("6. prediksi_naive_bayes_pso.csv")


=== HASIL EVALUASI NAIVE BAYES ===
Accuracy : 0.43805309734513276
Precision: 0.5357895370537595
Recall   : 0.43805309734513276
F1-Score : 0.4644465145163794

Classification Report Naive Bayes:
              precision    recall  f1-score   support

     negatif       0.40      0.50      0.45        34
      netral       0.20      0.40      0.26        43
     positif       0.66      0.44      0.53       149

    accuracy                           0.44       226
   macro avg       0.42      0.44      0.41       226
weighted avg       0.54      0.44      0.46       226


Confusion Matrix Naive Bayes:
[[17  8  9]
 [ 2 17 24]
 [23 61 65]]

=== HASIL EVALUASI NAIVE BAYES + PSO ===
Accuracy : 0.4690265486725664
Precision: 0.566110090721879
Recall   : 0.4690265486725664
F1-Score : 0.4990277620130493

Classification Report Naive Bayes + PSO:
              precision    recall  f1-score   support

     negatif       0.53      0.47      0.50        34
      netral       0.20      0.42      0.27  